kind: pipeline
name: test

# workspace:
#   path: /drone/src/github.com/nytimes/offer-presentation

steps:
- name: hello
  pull: if-not-exists
  image: alexwilkerson/hello
  # when:
  #   event:
  #   - push
  #   - tag
