---
kind: pipeline
name: default

steps:
- name: message
  image: alpine
  commands:
    - echo $DRONE_SEMVER

- name: hello
  pull: always
  image: alexwilkerson/drone-go-coverage:latest
  cmds:
    - which go
  settings:
    coverage_threshold: 50
